#!/bin/bash

BT=""

MAC=$(bluetoothctl devices | grep BUDS | cut -d' ' -f2)
CON=$(bluetoothctl info $MAC | grep 'Connected' | cut -d':' -f2)
if [[ $CON =~ 'yes' ]]; then
    BT="🎧"
fi

MAC=$(bluetoothctl devices | grep MOUSE | cut -d' ' -f2)
CON=$(bluetoothctl info $MAC | grep 'Connected' | cut -d':' -f2)
if [[ $CON =~ 'yes' ]]; then
    BT+="🖱️"
fi

if [[ -z $BT ]]; then
    BT=""
    color="color='#FFFFFF'"
else
    color="color='#33FF33'"
fi

logo=''
echo "<span $color>$logo</span> $BT"
