#!/bin/bash

location=
api=

curl https://api.forecast.io/forecast/$api/$location > /tmp/weather

weather=$(cat /tmp/weather)

#[[ -n $weather ]] &&  temp=$(echo $weather | awk -F '"temperature":' '{print int(($2-32)/1.8+0.5)}')

[[ -n $weather ]] && temp=$(echo "( $(echo $weather | jq -M '.currently.temperature' | tr -d '"') -31.1)/1.8" | bc)

[[ -n $weather ]] && echo "$temp°C"

